version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "@angular-devkit/*"
      angular-eslint:
        patterns:
          - "@angular-eslint/*"
